/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'alberto' at '9/21/15 7:28 AM' with Gradle 2.1
 *
 * @author alberto, @date 9/21/15 7:28 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
