/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'alberto' at '10/14/15 7:53 PM' with Gradle 2.1
 *
 * @author alberto, @date 10/14/15 7:53 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
