/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'alberto' at '9/21/15 7:28 AM' with Gradle 2.1
 *
 * @author alberto, @date 9/21/15 7:28 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
